In [1]:
import pandas as pd

In [9]:
xlsfile = pd.ExcelFile('sample_excel.xlsx')

In [16]:
dFrame = xlsfile.parse('VISUALIZATION')

In [17]:
dFrame

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,RISK LEVEL,RISK TIER,UCSD RISK,NaN,NaN
1,LOW,583,887,NaN,NaN
2,MEDIUM,604,207,NaN,NaN
3,HIGH,106,199,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN
8,RISK LEVEL DEFINITIONS,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN
10,UCSD RISK,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN
12,RISK LEVEL,RISK SCORE,NaN,NaN,NaN
13,LOW,0-0.5,NaN,NaN,NaN
14,MEDIUM,0.5-1,NaN,NaN,NaN
15,HIGH,>1,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN
17,RISK TIER,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN
19,LOW,No ED in last 12 months (AND) No hospitilizati...,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN
22,MEDIUM,1-3 ED in last 12 months (OR) 1 hospitilizatio...,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN
26,HIGH,>3 ED in last 12 months (OR) >1 hospitilizatio...,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN